### PR TITLE
Added IXYS_GUFP 3D source file

### PR DESCRIPTION
**Pull request by aris-kimi**

### CODE REVIEW

**Comment by aris-kimi** [comment]
@chschlue i think i managed to fix the red ones noted, but i haven't manage to fix the pink ones, i do not know why. If that PR gets accepted i will commit to footprint's PR those 3D files.

**Comment by chschlue** [comment]
The pink ones aren't really deal breakers as they're within tolerance.
I was just wondering how you arrived at these strange dimensions. Did you start out in imperial units?

**Comment by aris-kimi** [comment]
To be honest i do not know... :-/ I always use mm, i tried to found out why but it seems easier if i start a new one, which i am trying to avoid. But this PR surely got my wings beaten.. because i have more PRs open and i know they are pretty much worst than this one.

**Comment by aris-kimi** [comment]
@chschlue , I have moved the body at the against direction because i lost center of PTHoles, i think it is better now.

**Pull request merged**
