### PR TITLE
MountyRox: Battery holder type Eagle 12BH611added.

### PR DESCRIPTION
**Pull request by MountyRox**
Battery holder type Eagle 12BH611 for 9V battery added.
Reference footprint:
   Battery.pretty\BatteryHolder_Eagle_12BH611-GR.kicad_mod

 On branch mountyrox_batteryHolder
 Changes to be committed:
	new file:   Battery.3dshapes/BatteryHolder_Eagle_12BH611-GR.FCStd

Battery holder on footprint (side, top and top view)
bh1
bhtop
bh_bot

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @MountyRox , thank you for this contribution.
I think body needs to be moved in order to fit right inside silkscreen.

εικόνα
εικόνα

Do not start fixing yet, when i will finish this review i will comment again.

Best regards,
Aris

**Comment by MountyRox** [comment]
Hi Aris,
you are right, something is wrong. I fear my 3D model and also the footprint are wrong. If you look to the datasheet of the holder the lower mounting hole is in the center of the housing, but the two upper mounting holes are not. The distance from the left hole to the left edge of the housing is 12.5 mm; the distance from the right hole to the right edge of the housing is 14 mm:

 
image

Both in my 3D model and in the footprint the lower mounting hole is in the center of the upper two, which is wrong. This leads to the shift of the body against the lines on the silkscreen.

How should we proceed? If you wish, I can fix both.
Best wishes
Joerg

**Comment by aris-kimi** [comment]
Thank you @MountyRox , if you like yes, you may open a PR proposing a fix for fp, and fix also this one.

I confirmed from fp:
εικόνα

Only down hole needs to change `0.75mm` to share the difference.

**Comment by chschlue** [comment]
Adjust the model to fit a broken footprint? Why?

**Comment by aris-kimi** [comment]
@MountyRox , a proposed fix for the footprint then must be presented first, in order to continue with this PR.
A correct model for a broken footprint also cannot be accepted.

@chschlue , my bad, wasn't sure for how to handle that. I think above comment is ok.

**Comment by MountyRox** [comment]
I corrected the footprint by shifting the lower hole by 0.75 mm to the left and also corrected the 3D model. Now everything looks OK for me. But unfortunately I have following problem when starting a PR for the footprint:

My forked MountyRox/kicad-footprint/master tells me I am 1 commit ahead and if I start a pull request I have two changed files in the list: The corrected footprint of Eagle-12BH611 and still the file from my last PR #2425    (https://github.com/KiCad/kicad-footprints/pull/2425)
Please can someone tell me the right workflow after a PR to be correctly synchronised with the upstream/master again? In the past I always deleted the complete fork and the local clone and then I started forking and cloning again. But this can`t be the right procedure.

**Comment by chschlue** [comment]
```
git fetch <remote>
git checkout master
git reset --hard <remote>/master
```

Replace `<remote>` with what you chose to call the upstream remote (i.e. github.com/KiCad/kicad-footprints)

**Comment by MountyRox** [comment]
That doesn't help. My origin/master is still 1 commit ahead and when starting a new PR I always have the old file "Buzzer_Beeper.pretty/MagneticBuzzer_Kobitone_254-EMB84Q-RO.kicad_mod" from my last PR in my new PR.
Here is how it looks:
image

**Comment by aris-kimi** [comment]
Hi @MountyRox , if i understood correct, you can choose and delete the previous file.

You can avoid this fork/unfork by create a branch for every PR you intend to create, from your screenshot you are on your fork's master, check the differences with KiCAD's master, delete everything that shouldn't be there, sync it with kicad, and create a new branch, from there you will upload again in the correct directory and you compare and prepare a PR..
This way you can manage your PRs from your branches.

Hope this helped.

**Comment by MountyRox** [comment]
Hi Aris-Kimi, when i did my last PR i did this from a new branch (mountyrox_BugfixMagneticBuzzer) now i created again a new branch before i worked on the battery holder Eagle (branch "mountyrox_BhEagle"). With this branch i did a commit and a push. But if i start a PR from the branch containing the changes of the battery holder Eagle the 'old' MagneticBuzzer file is again part of this PR. Here you see it: 

image

May be i should have done some git commands after my last PR to avoid this behaviour? But i do not know what i should have done? 

I tried to delete the MagneticBuzzer file, but i have to commit this delete process.  I am not sure if this is what i want to do????
For me as a git newbie contributing to GitHub and git is still a mystery.

**Comment by aris-kimi** [comment]
I saw this unwanted in this PR file exists both on your branch and on master branch. You have to update the content of your files from your master and branches.
This issue happened because you did changes in your master and you had created branches from a this changed" master branch.
I hope this clears things up.

**Comment by chschlue** [comment]
Please don't fudge around the problem and instead actually reset your fork's master to upstream master.

Trying to manually "sync" your fork will only lead to ugly future PRs containing unnecessary commits because the actual git commit objects on your branch aren't the same as on upstream/master even though the result appears the same.

Note: I think when following my comment above, you probably tried to reset master to origin/master, which is most probably your fork, not the upstream repo. You have to add a git remote for KiCad/... not MountyRox/... (commonly called 'upstream')

**Comment by MountyRox** [comment]
Thanks for your comments.
I will delete my kicad-footprint fork and create a new one and then i make a new PR with the fixed BhEagle footprint. When this process is finished i commit the changes of the 3D file to this PR #290 .
I think this is the best way to proceed.

**Comment by chschlue** [comment]
FP fix merged.

**Comment by aris-kimi** [comment]
Thanks @chschlue , 
@MountyRox , now waiting for changes in this PR and also new 3D models: https://github.com/KiCad/kicad-packages3D/pull/720

**Comment by MountyRox** [comment]
Here are the new drawings with the updated kicad footprint:
bh_bot
bh1
bhtop

**Comment by MountyRox** [comment]
@aris-kimi commit with updated 3D models already in: KiCad/kicad-packages3D#720

**Comment by aris-kimi** [comment]
Thank you also for applying changes. Merging.

**Pull request merged**
