### PR TITLE
Adding trim_step source file to remove duplicate lines from STEP files

### PR DESCRIPTION
**Pull request by sethhillbrand**
This source file will take a STEP file and in-place replace it with a shrunk version that removes the duplicate lines and replaces them with a reference to the original line.

### CODE REVIEW

**Comment by sethhillbrand** [comment]
Re-pushed the commit with a bug fix to deal with lines that have more than one '='

**Comment by antoniovazquezblanco** [comment]
@sethhillbrand I am trying to do some cleanup of KiCad GH issues and PRs. I have seen the thread in https://github.com/KiCad/kicad-packages3D/pull/223. It seems changes will not be merged. Should we close this PR also or is this work check pending?

BTW I am interested in this size srinking but seems a little bit unstable. Have you tryed to contribute to FreeCAD or OCC given your knowledge of the STEP file format? It would be nice to see this improvements without having to bypass file generators or without having to process STEP files twice. :)

**Comment by sethhillbrand** [comment]
@antoniovazquezblanco The code as is has no known issues.  That said, it is only tested against the models in the KiCad repository.

**Comment by Shackmeister** [comment]
Hi @sethhillbrand

Could you possibly create an issue over at the OCC Developer page, describing this approach? http://git.dev.opencascade.org/gitweb/?p=occt.git

If there should be any issues with it, I believe these guys would be able to point it out, if not I would love to see it in the OCC kernel! If we could get to that point, we could respin all the generator scripts to shrink the entire repo.

**Pull request closed without merging**
