### PR TITLE
Added the first draft of ESP-WROOM-32 module, work in progress

### PR DESCRIPTION
**Pull request by sandhan26**
## To Do List
- [x] Create the first draft of the 3D model for ESP-WROOM-32 module.
- [x] Dimensions of the 3D model created as per [datasheet](https://www.espressif.com/sites/default/files/documentation/esp-wroom-32_datasheet_en.pdf)
- [ ] To figure out an easy way to add the graphics.
- [ ] To Export the finished model to STEP and WRL, and create a pull request to https://github.com/KiCad/kicad-packages3D

esp-32-1
esp-32-2
esp-32-3

### CODE REVIEW

**Comment by sandhan26** [comment]
@evanshultz @jkriege2 @Misca1234 @poeschlr @Shackmeister : Any suggestions on padding a binary image in FreeCAD?

**Comment by poeschlr** [comment]
Maybe move the image to a "img" subfolder and name it `texture_[componentName]` to make it clear what it is used for.

**Comment by sandhan26** [comment]
@poeschlr can you advice me on any technique to pad/extrude a binary image in freecad?

**Comment by poeschlr** [comment]
Thanks for your contribution.

**Pull request merged**
