### PR TITLE
Esp32 wroom

### PR DESCRIPTION
**Pull request by Misca1234**
Here is the script files for the 3D models for

ESP-WROOM-32
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf

ESP-WROOM-32U
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

ESP-WROOM-32D
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

See foot print push 
https://github.com/KiCad/kicad-footprints/pull/647

See 3D model push
https://github.com/KiCad/kicad-packages3D/pull/337

We have a slight problem here

1)
There is a very nice, almost too nice made 3D model for the ESP-WROOM-02 in 
https://github.com/KiCad/kicad-packages3D/RF_Module/ESP-WROOM-02.wrl
But there is no .FCStd file in kicad-packages3D-source

Therefore if you bring up the ESP-WROOM-02.FCStd in this push, it does not look the same.
I have tried to contact the guy that "made" the original .wrl file to see if he could push 
the .FCstd file to the ESP-WROOM-02.wrl but have not got any response.

2)
There is a very nice, almost to nice, ESP-WROOM-32.FCStd file but no generated 
ESP-WROOM-32.wrl file.
I have asked the guy who pushed the .FCStd file to see if he could make the .wrl file and push it 
but no response.

Therefore:
a)
My ESP-WROOM-02.FCStd is included in this push, but I have not pushed the .wrl/.step file for this source file to avoid to write over the the very nice .wrl model, but in case we need to generate 
the ,wrl file again we have at least some .FCStd file
b)
I have pushed a 3D ESP-WROOM-32.wrl which is based on my file ESP-WROOM-32 (2).FCStd file. 
(therefore the very nice ESP-WROOM-32.FCStd is keept.

My question is, because the original author does not respond and we really do not know where the 
ESP-WROOM-32.FCStd and ESP-WROOM-02.wrl comes from.
Shall I replace those with my files ?

### CODE REVIEW

**Comment by Misca1234** [comment]
They are renamed into the correct name, that is "ESP-WROM... " into "ESP32-WROM..."

**Comment by antoniovazquezblanco** [comment]
Thanks @Misca1234!

**Comment by Misca1234** [comment]
What should we do with the almost to nice .Fcstd and .wrl files ?

**Comment by antoniovazquezblanco** [comment]
I believe that the source file should be named as the 3D file. If your 3D files have been merged we should name the source files as those (just to know from where they came).

Now about the almost too nice WRL, I would prefer to have a file with a know source model that is not as nice as the current one but that we know that surely complies with licensing and that we can regenerate. If we cannot get the source of the model I would vote for overriding it.

Anyways I believe that this decision is over my level of command. Should we invoke @poeschlr?

**Comment by easyw** [comment]
Are you talking of this file?
https://github.com/KiCad/kicad-packages3D-source/blob/master/RF_Module.3dshapes/ESP-WROOM-32.fcstd

**Comment by Misca1234** [comment]
Yes

**Pull request merged**
