### PR TITLE
TE Connectors 1217861-1, 0.250 QC THT male tab

### PR DESCRIPTION
**Pull request by chmorgan**

### CODE REVIEW

**Comment by easyw** [comment]
Hi @chmorgan 
have you designed the 3d model in FC? Or you just aligned the TE model to kicad fp?

**Comment by chmorgan** [comment]
Hi @easyw. I have added those models as per the klc document using the TE model as a starting point.

I've added PRs against packages3D and packages3D-source with the 3d model via FC and the stepup scripts and verified alignment in the 3D view of the kicad footprint editor. I can paste the links to the PRs here.

**Comment by easyw** [comment]
Hi @chmorgan 
if you used the TE model as starting point, then the 3d model wouldn't be possible to add this model to the repo because of restrictions in the 3d model licence
Please have a look at this link
https://github.com/KiCad/packages3D/wiki/Contributing
particularly

> Contributing to this lib generally requires that the person committing the files is the current license holder. (Easiest way: The contributor created the models.) Sometimes it is tempting to contribute models of a third party. (Example a manufacturer supplied model) In most cases these models are licensed under an incompatible license. To accept such models we need the explicit consent by the current license holder that the models will be licensed under the license of our library. (GPLv3 with symbol exception.)

**Comment by chmorgan** [comment]
Hi @easyw. I'm reaching out to TE to see what their license on those models is. The most optional approach imo would be if they said the models were free to use for any purpose. Next best option is I'll have to re-create them not based on their designs or just focus on getting the footprint in without the 3D model.

Is it possible/ok to get the footprint in without the 3D model? I'm looking to make some kind of progress here and/or help to facilitate that in any way I can.

**Comment by poeschlr** [comment]
You can add a footprint with out a 3d model. The only requirement is that the footprint has the 3d model settings filled out correctly such that it is possible to add a model without changing the footprint.

**Comment by chmorgan** [comment]
@poeschlr ahh ok. Well I'm hoping the footprint is reviewed and accepted and I'll post an update if I heard back from TE or create a 3D model from the drawings they provide.

**Comment by poeschlr** [comment]
I assume you never heard back from TE.

**Comment by chmorgan** [comment]
Yep, never heard back from them.

**Pull request closed without merging**
