### PR TITLE
Create Potentiometer_Bourns_3339P_Vertical.fcstd

### PR DESCRIPTION
**Pull request by ferdymercury**
https://github.com/KiCad/kicad-packages3D/pull/431

### CODE REVIEW

**Comment by easyw** [comment]
@Misca1234, I have done a look at the [FC source file](https://github.com/KiCad/kicad-packages3D-source/pull/176) and inside it there is just the STEP file, colored and aligned... @ferdymercury it seems to me that your model is just a rearrangement (changing colors, label and placement) of the model downloaded from the Bourns site... Have you designed the model or you just rearranged the available model in internet to fit KiCAD footprint?

**Comment by Misca1234** [comment]
@easyw 
How do you see if they are downloaded from the manufacture side? 
My only way to detect it is to be suspicious when the model looks too good.

@ferdymercury 
I can make this model if you don't know how to use 3D cad tools?

**Comment by ferdymercury** [comment]
@easyw Oops, I did not know that I had to redesign the piece by myself, my apologies. I thought it was enough to rotate and recolour the original piece.

**Comment by Misca1234** [comment]
@ferdymercury 
Np, I should have investigated it more, however I have recreated them here
https://github.com/KiCad/kicad-packages3D-source/pull/181

**Comment by ferdymercury** [comment]
Great, thanks.

**Comment by easyw** [comment]
@ferdymercury 
no problem at all... we just need to keep the library full open source 😄 
@Misca1234 may be we should add some lines to [README file](https://github.com/KiCad/kicad-packages3D-source/blob/master/README.md) to highlight that the Native 3D model Files have to be entirely done from original artwork.

**Pull request merged**
