### PR TITLE
CadQuery source for Molex 502250 FFC connectors

### PR DESCRIPTION
**Pull request by jhol**

### CODE REVIEW

**Comment by poeschlr** [comment]
Do you know about https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator?
There are supporting scripts that allow automatically exporting a complete series of models from cadquerry models.
For inspiration have a look at the molex subfolder for details.

**Comment by jhol** [comment]
@poeschlr Will it be necessary for me to integrate my code with the script generator, in order to get my 3D models integrated in this instance? I don't mind doing it, but I've spent more time on this than I really want to already, but if there's no other way I guess I'll bite the bullet and finish the job.

My experience so far is that I've had to redo my submissions several times, because I wasn't aware of the right way to do things. Your comments are really helpful - thanks for taking the time to set me straight, but at the moment my I only way to get that feedback is after I've already finished doing things the wrong way.

Is there a way to talk to the library maintainers? Do you guys lurk on IRC? Or is there a mailing list for this?

Some of this is my own fault for not reading the docs carefully enough, but I think it would help drive-by contributors a lot if you folks could put some time into simplifying the `README.md` files. I reinvented the wheel several times, because I wasn't aware that these problems had already been solved in that repository, that I had no idea existed. For example, I was looking for a canonical way to make 3D connector models with open source software, but in my searching I just found a lot of conflicting, incomplete and obsolete information. It would help a lot if you guys could improve the landing pages to prevent people getting lost.

The background to this is that I'm the guy behind [OpenTechLab](https://www.youtube.com/channel/UCeF7JKNXOy0jpMOxpgbZcpg/videos) - a small YouTube channel focused on open source and electronics, and I'm working on a video in which I talk about an electronics project that prompted all this. I plan to talk about how I contributed to the kicad libraries. My message from this is...

> "Contributing to the libraries is a good idea - please take the time to do it. I was unlucky that I arrived just when major (positive) changes were being made, and there was a lot of conflicting information hanging around, and I wasted time reinventing the wheel by accident. However, don't be put off because things are getting much better - you can do all this cool stuff with these scripts and FreeCAD/StepUp/CadQuery, so if you're in doubt go ${HERE} where you can find out exactly what to do".

...does that make sense? I'd like to make it as easy as possible for my viewers to make correct contributions efficiently so that the library will grow.

I don't know if this is the right place to discuss these things, but I'd be interested to know your opinion.

**Comment by poeschlr** [comment]
Well look at this: https://github.com/easyw/kicad-3d-models-in-freecad/issues/145 i intend on doing something about it.

For now i would suggest you make a pull request on that repo instead of here. Add your script to the cq_models subfolder under the molex generators and notify me. If i find time i will integrate your stuff into the molex generator.

**Comment by easyw** [comment]
@jhol I can understand your frustration
> My experience so far is that I've had to redo my submissions several times, because I wasn't aware of the right way to do things.

@poeschlr @jhol 
till now the most representative place to get information on making a 3D model to be included in KiCad 3D libraries has been only the KiCad info forum.
I think the best would be to have a chapter in KiCad Manual to describe the up to date process and the tools involved in.
That will give users a solid reference and it will be fast indexed by searching engines.

@poeschlr I think the library is one extremely important milestone on which a KiCad project can safely grow. I think it should be some room in the manual to give to the libraries and their way to build a place to help users in contribute easily.

**Comment by jhol** [comment]
> @jhol I can understand your frustration

@easyw - no don't worry I'm not really frustrated. You guys are doing excellent work. I'm amazed how much better the library has got in the last year. You're all doing great work; keep it up.

**Comment by jhol** [comment]
This merge request has been superceded by this one: https://github.com/easyw/kicad-3d-models-in-freecad/pull/146

**Pull request closed without merging**
