### PR TITLE
Add ESP-12E

### PR DESCRIPTION
**Pull request by tadas-s**
Hello,

Made mostly from scratch with FreeCAD 0.17 with exception of the led
which was imported from existing kicad 3d component library.

I'm new to FreeCAD so I'm not entirely sure if it's acceptable quality or not. All feedback welcome.

Exported `.step` file fits existing ESP-12F footprint in the built-in KiCad library (see screenshots).

## Screeshots

FreeCAD screenshot below + see "in action" KiCad screenshots in the related PR: https://github.com/KiCad/kicad-packages3D/pull/517

screenshot from 2019-01-29 21-14-44

### CODE REVIEW

**Comment by Shackmeister** [comment]
This looks awesome! 
Drawn quality is absolutely enough.
Now we just need to make sure it's exported properly.
you should make a PR at https://github.com/KiCad/kicad-packages3D

**Comment by tadas-s** [comment]
@Shackmeister sure, will do.

**Comment by tadas-s** [comment]
@Shackmeister https://github.com/KiCad/kicad-packages3D/pull/517
Screenshots in that PR look a little different with KiCad StepUp applied materials. I haven't saved the changes KiCad StepUp makes since it kind of messes up the object tree :man_shrugging:

**Comment by easyw** [comment]
that depends on how you use the wb tools

**Comment by tadas-s** [comment]
OK. Update of the PR: forget ESP-12F for now, this only adds ESP-12E which is already in the component / footprint library.

**Pull request merged**
