### PR TITLE
Add 3d model for Converter_ACDC_HiLink_HLK-PMxx

### PR DESCRIPTION
**Pull request by BoresXP**
Source file (FreeCAD 0.18) for this models:
https://github.com/KiCad/kicad-packages3D/pull/556

### CODE REVIEW

**Comment by VictorLamoine** [comment]
@BoresXP Can you reopen this merge request so that the 3D model is added to KiCAD 3D packages ?

**Comment by BoresXP** [comment]
> @BoresXP Can you reopen this merge request so that the 3D model is added to KiCAD 3D packages ?
I've added it another way:
https://github.com/easyw/kicad-3d-models-in-freecad/pull/293
Do you still need me to open this PR?

**Comment by chschlue** [comment]
No, not this one.

But the actual models have to be pushed to packages-3D

**Comment by BoresXP** [comment]
Do I still need to do something?

**Comment by chschlue** [comment]
Yes, please reopen https://github.com/KiCad/kicad-packages3D/pull/556 and push the generator's output there.

**Pull request closed without merging**
